include: package:pedantic/analysis_options.yaml

linter:
  rules:
    - avoid_print

analyzer:
  exclude:
    - lib/**.g.dart
    - lib/**.freezed.dart
  errors:
    invalid_use_of_visible_for_testing_member: error
    must_be_immutable: error
  strong-mode:
    implicit-casts: false
    # implicit-dynamic: false
