name: backend
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  pedantic: ^1.8.0
  shelf: ^0.7.5
  shelf_router: ^0.7.2
  json_rpc_2: ^2.1.0
  stream_channel: ^2.0.0
  web_socket_channel: ^1.1.0
  shelf_web_socket: ^0.2.3
  postgres: ^2.1.0
  postgres_pool: ^2.0.1
  logging: ^0.11.4
  crypto: ^2.1.4
  meta: ^1.1.8
  http: ^0.12.0+4
  freezed_annotation: ^0.7.1
  json_annotation: ^3.0.1
  uuid: ^2.0.4
  retry: ^3.0.0+1

dev_dependencies:
  shelf_router_generator: ^0.7.0+1
  build_runner: ^1.3.1
  test: ^1.6.0
  mockito: ^4.1.1
  freezed: ^0.10.5
  json_serializable: ^3.0.0
