name: CD on master

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Rm backend folder
        run: |
          ssh root@51.15.215.104 'rm -rf backend'
      - name: Create backend folder
        run: |
          ssh root@51.15.215.104 'mkdir backend'
      - name: Upload backend
        run: |
          scp -r bin lib pubspec.yaml pubspec.lock tools root@51.15.215.104:/root/backend
      - name: Connect to server and launch new version
        run: |
          ssh root@51.15.215.104 '~/.bashrc;cd /root/backend/;tools/deploy.sh'
