name: CD on master

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          config: ${{ secrets.CONFIG }} # ssh_config; optional
      - name: Upload backend
        run: |
          scp -r bin lib pubspec.yaml pubspec.lock root@51.15.215.104:/root/backend
      - name: Connect to server and launch new version
        run: |
          ssh root@51.15.215.104
          pub get
          killall dart
          dart bin/main.dart > backend.log &
          exit
