name: Deploy to staging

on:
  push:
    tags:
      - "*-staging.*"

jobs:
  build_and_deploy_to_staging:
    runs-on: ubuntu-latest
    container:
      image: google/dart:latest
    steps:
      - uses: actions/checkout@v2
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Pub get
        run: pub get
      - name: Build
        run: pub run build_runner build
      - name: Compile
        run: dart2native bin/main.dart
      - name: Upload backend binary
        run: |
          scp -i .ssh/id_rsa -r bin/main.exe root@51.15.141.25:/root/bin
      - name: Launch
        run: |
          ssh -i .ssh/id_rsa root@51.15.141.25 /bin/bash << EOF
            killall main.exe || echo "Process was not running."
            bin/main.exe >> backend.log &
          EOF
